# Generated by Django 3.2.6 on 2021-09-15 14:49

from django.db import migrations, models
import django.db.models.deletion
import placegallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InterestingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesting_place_name', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=10)),
                ('cord_x', models.FloatField()),
                ('cord_y', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placegallery.city')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=placegallery.models.create_image_path)),
                ('interesting_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placegallery.interestingplace')),
            ],
        ),
    ]
