# Generated by Django 3.2.6 on 2021-09-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interestingplace',
            name='interesting_place_name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
