# Generated by Django 3.2.6 on 2021-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0002_auto_20210917_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='interestingplace',
            name='interesting_place_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
