# Generated by Django 3.2.6 on 2021-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0003_auto_20210917_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='interestingplace',
            name='interesting_place_name',
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interestingplace',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interestingplace',
            name='interesting_place_name_ru',
            field=models.CharField(max_length=200),
        ),
    ]
