# Generated by Django 3.2.6 on 2021-09-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0004_auto_20210917_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interestingplace',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
