# Generated by Django 3.2.6 on 2021-09-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0005_auto_20210917_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestingplace',
            name='street_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
