# Generated by Django 3.2.6 on 2021-09-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0006_alter_interestingplace_street_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestingplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='placegallery.city'),
        ),
    ]
