# Generated by Django 3.2.6 on 2021-09-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0007_alter_interestingplace_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name_ru', models.CharField(max_length=50, verbose_name='russian name')),
                ('population', models.IntegerField(blank=True)),
                ('area', models.FloatField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=50, verbose_name='russian name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='english name for URL'),
        ),
        migrations.AlterField(
            model_name='interestingplace',
            name='cord_x',
            field=models.FloatField(verbose_name='X coordinate'),
        ),
        migrations.AlterField(
            model_name='interestingplace',
            name='cord_y',
            field=models.FloatField(verbose_name='Y coordinate'),
        ),
        migrations.AlterField(
            model_name='interestingplace',
            name='interesting_place_name_ru',
            field=models.CharField(max_length=200, verbose_name='russian name'),
        ),
        migrations.AlterField(
            model_name='interestingplace',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='english name for URL'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='placegallery.region'),
        ),
    ]
