# Generated by Django 3.2.6 on 2021-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0008_auto_20210927_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
