# Generated by Django 3.2.6 on 2021-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0009_auto_20210927_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
