# Generated by Django 3.2.6 on 2021-10-07 23:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placegallery', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placegallery.interestingplace'),
            preserve_default=False,
        ),
    ]
